name: Lint and format then tests and PR pipeline 

on: 
  push:
    branches-ignore:
      - 'lap'
      - 'stage'
      - 'main'

permissions:
  contents: write
  packages: write

jobs:
  lint_and_format:
    uses: Vronst/lint-check/.github/workflows/lint.yaml@1.0.0
    # (optional)
    with:
      python-version: '3.13'


  tests:
    uses: Vronst/testing_workflow/.github/workflows/testing_workflow.yml@2.1.0
    with:
      container_name: 'paytrack'


  create_PR:
    needs: 
      - tests
      - lint_and_format
    uses: Vronst/pull_request_workflow/.github/workflows/pull_request.yml@1.1.0
    with:
      head: ${{ github.even.workflow_run.head_branch }}
      base: 'lap'
      title: 'Tests_and_style_formatting_have_passed'
      body: 'Minimal_requirements_for_pr_to_"lap"_have_been_met'
      flag: '--draft'
    secrets:
      TOKEN: ${{ secrets.PRO_TOKEN }}
