name: Create Release on Main

on:
  push:
    branches:
      - main  
  pull_requests:
    branches:
      - main

permissions:
  contents: write    # required for creating releases
  pull-requests: write

jobs:
  test-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          if [ -f requirements.txt ]; then uv add -r requirements.txt; fi
          uv sync --frozen
      
      - name: Run regression tests
        run: uv run pytest
      
      - name: Run release preparation script
        run: |
          release

      - name: Create release notes
        if: success()
        run: |
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          cat release-notes.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create release and new tag
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
          RELEASE_NOTES: ${{ env.RELEASE_NOTES }}
          GITHUB_TOKEN: ${{ secrets.PRO_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$RELEASE_VERSION" -m "$RELEASE_NOTES"
          git push origin "$RELEASE_VERSION"
          gh release create "$RELEASE_VERSION" --notes "$RELEASE_NOTES"
