name: Tests and Pull Request Pipeline

on:
  push:
    branches:
      - stage

# needed permissions
permissions:
  contents: write
  packages: write

jobs:
  tests:
    uses: Vronst/testing_workflow/.github/workflows/testing_workflow.yml@2.1.0
    with:
      container_name: 'paytrack'

  lint_and_format:
    uses: Vronst/lint-check/.github/workflows/lint.yaml@1.0.0
    # (optional)
    with:
      python-version: '3.13'

  create_PR:
    needs: 
      - tests
      - lint_and_format
    uses: Vronst/pull_request_workflow/.github/workflows/pull_request.yml@1.2.1
    with:
      head: 'stage'
      base: 'main'
      title: 'Tests passed'
      body: 'Tests on Stage branch has passed.'
    secrets:
      TOKEN: ${{ secrets.PRO_TOKEN }}


